stages:
- stage: stage1
  pool:
    vmImage: 'ubuntu-latest'
  jobs:
  - job: job1
    steps:
    - task: AzureRmWebAppDeployment@4
      inputs:
        ConnectionType: 'AzureRM'
        azureSubscription: 'Assinatura do Azure 1(1)(6f5391e6-0869-48a4-b92c-9cbbe3e187e9)'
        appType: 'webApp'
        WebAppName: 'eshop-dev'
        packageForLinux: '.'
