  trigger: none

  variables:
    dotNetVersion: "6.0.x"
    buildConfiguration: "Release"

  stages:
  - stage: Build
    jobs:
    - job: Build
      steps:
      - task: UseDotNet@2
        inputs:
          version: $(dotNetVersion)
          includePreviewVersions: true
      - task: DotNetCoreCLI@2
        inputs:
          command: 'restore'
          feedsToUse: 'select'
      - task: DotNetCoreCLI@2
        displayName: "Build"
        inputs:
          command: "build"
          arguments: "--configuration $(buildConfiguration)"
    
      - task: DotNetCoreCLI@2
        displayName: "Test"
        inputs:
          command: "test"
          projects: "**/*Tests/*.csproj"
          arguments: "--configuration $(buildConfiguration)"

      - task: DotNetCoreCLI@2
        displayName: "Publish"
        inputs:
          command: 'publish'
          publishWebProjects: false
          zipAfterPublish: false
          modifyOutputPath: false
          projects: "**/*.csproj"